### ISSUE TITLE
Printing Issue in CustomReportViewer

### ISSUE THREAD

**Issue by AnshQTK** [LanceMcCarthy/CustomMauiExamples#17]
Hello,

I downloaded your CustomReportViewer project to my local device and attempted to print the demo report, but encountered an issue – it didn't print. Subsequently, I tried to save it on my computer using the printer dialog, and it saved as a PDF. However, when I attempted to open the PDF, I received an error message stating, "We can't open this file. Something went wrong."

Thanks

**Comment by LanceMcCarthy** [comment]
Hi @AnshQTK that's for Telerik Reporting, not really PDF processing. I didn't vet any of the actual PDF files or data as the idea is to just show that you can create a custom control, add some dependency properties and wire up those properties to the native control. This isn't worth developing any further until the WinUI3 API resolution issue is improved.

If you're still looking for "Printing a PDF file from a WinUI3 project" (which includes .NET MAUI project, because it is a WinUI app on Windows)), then you might want to check out the Telerik UI for WinUI PdfViewer, which has printing support 

https://docs.telerik.com/devtools/winui/controls/radpdfviewer/printing





If you are actually trying to use `Telerik Reporting` support in WinUI3 project, then you can just use the WinUI ReportViewer. See the following docs:
- https://docs.telerik.com/reporting/embedding-reports/display-reports-in-applications/winui-3-desktop-application/overview
- https://docs.telerik.com/reporting/embedding-reports/display-reports-in-applications/winui-3-desktop-application/how-to-add-report-viewer-to-a-.net-5-application

For help with Telerik Reporting, you can talk to the Telerik Reporting team here => https://www.telerik.com/account/support-center/contact-us/technical-support

**Comment by LanceMcCarthy** [comment]
I was able to replicate the "Print To PDF" corruption you mentioned. 

As far as exporting as PDF goes, there is a `System.IO.IOException` that occurs. This is probably due to project settings/permissions that need to be added or enabled. You can ask the Telerik Reporting team for help with this, or take a look at their demos source code. It's already installed on your machine if you have Telerik Reporting, go to `C:\Program Files (x86)\Progress\Telerik Reporting R3 2023\Examples\CSharp` and open `CSharp.WinUIExample.VS2022.sln`
