### ISSUE TITLE
Question: printing without dialog

### ISSUE THREAD

**Issue by jt-pt-dev** [LanceMcCarthy/CustomMauiExamples#21]
Hi,

Thank you for building these examples. They have been helpful. I am most interested in printing from MAUI. I have the DocumentPrinting demo working but have a question:

Is it possible to print without a dialog. The system we are building will run the MAUI app on a mobile device (iOS, Android or Windows; whichever one we can get running), and print to the default network printer. This is for a visitor system that prints stickers so we need 'silent' printing.

**Comment by jt-pt-dev** [comment]
I was primarily interested in printing PDFs with this project and found a solution for silent printing.

https://github.com/billreiss/mauiSilentPrintPdf/issues/1

**Comment by LanceMcCarthy** [comment]
Thank you for sharing! I'll look at ways to add this as a toggleable flag to the existing helper class.

**Comment by LanceMcCarthy** [comment]
I had a chance to review this today, it looks like Bill is using FreeSpire.Pdf to print the document (rather than rolling your own like this project does).

For any future visitors to this Issue, here is how to replicate the desired outcome:

1. Install the [FreeSpire.PDF](https://www.nuget.org/packages/FreeSpire.PDF) NuGet package to the project. For example:

```xml
<PackageReference Include="FreeSpire.PDF" Version="8.6.0" />
```

2. Add the following using statements to the page:

```csharp
﻿using Spire.Pdf;
using Spire.Pdf.Print;
```

3. In your print button click event handler:

```csharp
PdfDocument pdf = new PdfDocument();
var fileName = "sample-pdf-file.pdf";

var stream = await FileSystem.OpenAppPackageFileAsync(fileName);
pdf.LoadFromStream(stream);

// In the settings object you can set the printer name and a lot of other options. No printer name prints to default.
PdfPrintSettings settings = new PdfPrintSettings();
settings.Color = false;

// OPTIONAL - FOR SILENT PRINT
settings.PrintController = new StandardPrintController();

pdf.Print(settings);
```
